#if !defined(USB_HID_TERNEL_PIN_MAP)
#define USB_HID_TERNEL_PIN_MAP

// #define ADC0 0
// #define ADC1 1
// #define ADC2 2 
// #define ADC3 3

#define KEY1    GPIOA,GPIO_PIN_4
#define KEY2    GPIOA,GPIO_PIN_5
#define KEY3    GPIOA,GPIO_PIN_6
#define KEY4    GPIOA,GPIO_PIN_7
#define KEY5    GPIOB,GPIO_PIN_0
#define KEY6    GPIOB,GPIO_PIN_1
#define KEY7    GPIOB,GPIO_PIN_2
#define KEY8    GPIOB,GPIO_PIN_10
#define KEY9    GPIOB,GPIO_PIN_11
#define KEY10   GPIOB,GPIO_PIN_12
#define KEY11   GPIOB,GPIO_PIN_13
#define KEY12   GPIOB,GPIO_PIN_14
#define KEY13   GPIOB,GPIO_PIN_15
#define KEY14   GPIOA,GPIO_PIN_8
#define KEY15   GPIOA,GPIO_PIN_9
#define KEY16   GPIOA,GPIO_PIN_10
#define KEY17   GPIOA,GPIO_PIN_15
#define KEY18   GPIOB,GPIO_PIN_3
#define KEY19   GPIOB,GPIO_PIN_4
#define KEY20   GPIOB,GPIO_PIN_5
#define KEY21   GPIOB,GPIO_PIN_6
#define KEY22   GPIOB,GPIO_PIN_7
#define KEY23   GPIOB,GPIO_PIN_8
#define KEY24   GPIOB,GPIO_PIN_9
#define KEY25   GPIOC,GPIO_PIN_13
#define KEY26   GPIOC,GPIO_PIN_14
#define KEY27   GPIOC,GPIO_PIN_15
#define KEY28   GPIOA,GPIO_PIN_13
#define KEY29   GPIOA,GPIO_PIN_14


#endif // USB_HID_TERNEL_PIN_MAP
